routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\PromotionController;
use App\Http\Controllers\Admin\MyController;
use App\Http\Controllers\Admin\UserExcelController;
use App\Http\Controllers\Admin\ConmmentController;

Route::group(['middleware' => ['check_login_admin'] , 'as' => 'admin.'], function () {

    Route::get('login', [AuthController::class, 'getLogin'])->name('login');
    Route::post('login', [AuthController::class, 'postLogin'])->name('login.handle');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');
	
	// Admin Dashboard
	Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/roleadmin', [DashboardController::class, 'role'])->name('roleadmin'); 

    // middleware check_role_sales: nếu role!= 1 && role != 2 thì không đc vào
    Route::middleware(['check_role_editer'])->group(function () { 
        Route::group(['prefix'=> 'category', 'as'=> 'category.'], function () {
            Route::get('/list', [CategoryController::class, 'index'])->name('index');
            Route::get('/create', [CategoryController::class, 'create'])->name('create');
            Route::post('/store', [CategoryController::class, 'store'])->name('store');
            Route::get('/show/{id}', [CategoryController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [CategoryController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [CategoryController::class, 'destroy'])->name('destroy');
        });

        Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
            Route::get('/list', [ProductController::class, 'index'])->name('index');
            Route::get('/create', [ProductController::class, 'create'])->name('create');
            Route::post('/store', [ProductController::class, 'store'])->name('store');
            Route::get('/show/{id}', [ProductController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [ProductController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix'=> 'message', 'as' => 'message.'], function () {
            route::get('/message',[MessageController::class, 'message'])->name('message');
        });
        Route::group(['prefix'  =>  'promotion'    ,   'as'    =>  'promotion.']  ,function(){
            route::get('/',[PromotionController::class,'promotion'])->name('list_promotion');
            Route::get('/create', [PromotionController::class, 'create'])->name('create');
            Route::post('/store', [PromotionController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [PromotionController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [PromotionController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [PromotionController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix'  =>  'comment', 'as' => 'comment.'], function (){
            Route::get('/', [ConmmentController::class, 'index'])->name('comment');
            Route::delete('/delete/{id}', [ConmmentController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
            Route::delete('/delete/{id}', [OrderController::class, 'destroy'])->name('destroy');
        });
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('/list', [OrderController::class, 'index'])->name('index');
        Route::get('/show/{id}', [OrderController::class, 'show'])->name('show');
        Route::get('/edit/{id}', [OrderController::class, 'edit'])->name('edit');
        Route::put('/update/{id}', [OrderController::class, 'update'])->name('update');
        // Route::delete('/delete/{id}', [OrderController::class, 'destroy'])->name('destroy');
    });
    // middleware admin: nếu role khác 1 thì không đc vào
    Route::middleware(['check_role_admin'])->group(function () { 
        Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
            Route::get('/list', [CustomerController::class, 'index'])->name('index');

            // Route::get('/create', [CustomerController::class, 'create'])->name('create');
            // Route::post('/store', [CustomerController::class, 'store'])->name('store');
            // Route::get('/search', [CustomerController::class, 'search'])->name('search');

            // Route::get('/show/{id}', [CustomerController::class, 'show'])->name('show');
            // Route::get('/edit/{id}', [CustomerController::class, 'edit'])->name('edit');
            // Route::put('/update/{id}', [CustomerController::class, 'update'])->name('update');
            
            Route::delete('/delete/{id}', [CustomerController::class, 'destroy'])->name('destroy');
        });

        Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
            Route::get('/list', [UserController::class, 'index'])->name('index');
            Route::get('/create', [UserController::class, 'create'])->name('create');
            Route::post('/store', [UserController::class, 'store'])->name('store');
            Route::get('/show/{id}', [UserController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [UserController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [UserController::class, 'destroy'])->name('destroy');

        });
            // excel Admin
            Route::get('/importExportView', [MyController::class, 'importExportView'])->name('importExportView');
            Route::get('/export', [MyController::class, 'export'])->name('export');
            Route::post('/import', [MyController::class, 'import'])->name('import');

            //excel user
            Route::get('CustomerExcel', [UserExcelController::class, 'importExportView'])->name('customerExcel');
            Route::get('ExportCustomer', [UserExcelController::class, 'ExportCustomer'])->name('ExportCustomer');
            Route::post('ImportCustomer', [UserExcelController::class, 'ImportCustomer'])->name('ImportCustomer');    
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderUserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\MessageController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/', [HomeController::class, 'index'])->name('index');

Route::group(['prefix' => 'home', 'as' => 'home.'], function () {
    
    Route::get('shop/{id}', [HomeController::class, 'shop'])->name('shop');

    });

Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('/detail/{id}', [ProductController::class, 'detail'])->name('detail');
    Route::post('/review', [ProductController::class, 'review'])->name('review');
    Route::get('/delete-comment/{id}', [ProductController::class, 'deleteComment'])->name('delete-comment');
    Route::get('/search', [ProductController::class, 'searchProduct'])->name('search'); 
    Route::get('/category/{id}', [ProductController::class, 'getProductByCategory'])->name('category'); 
        
    });
// route goij ddeens show ddaau hungf h
Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', [CartController::class, 'CartInfo'])->name('cart-info'); 
    Route::post('cart/{id}', [CartController::class, 'addCart'])->name('add-cart');
    Route::get('checkout', [CartController::class, 'checkout'])->name('checkout')->middleware('check_order');
    Route::post('checkout-complete', [CartController::class, 'Complete'])->name('checkout-complete');
    Route::post('send-verify-code', [CartController::class, 'sendVerifyCode'])->middleware(['auth'])->name('send-verify-code');
    Route::post('confirm-verify-code', [CartController::class, 'confirmVerifyCode'])->middleware(['auth'])->name('confirm-verify-code');
    Route::post('/delete', [CartController::class, 'destroy'])->name('destroy');
    
    });

Route::group(['prefix'  =>  'order_user', 'middleware' => 'auth',  'as'    =>  'order_user.']  ,function(){
    route::get('/',[OrderUserController::class,'order_user'])->name('list_order');
    route::get('/detail/{id}',[OrderUserController::class,'detailOrder'])->name('detail_order');
    Route::get('/profile',[OrderUserController::class,'profile'])->name('profile');
    Route::get('/edit', [OrderUserController::class, 'edit'])->name('edit');
    });

Route::group(['prefix'=>'contact', 'as'=> 'contact.'],function () {

        Route::get('/',[ContactController::class, 'contact'])->name('address');
        Route::post('/postmessage',[ContactController::class, 'postmessage'])->name('postmessage');
    });

Route::group(['prefix' =>'password','as'=>'password.'],function () {

    Route::get('/',[PasswordController::class, 'change'])->name('password');
    route::get('/detail/{id}',[PasswordController::class,'detailpassword'])->name('detailchange');
    Route::put('/update/{id}', [PasswordController::class, 'update'])->name('store');
});





app/Http/Controllers/OrderUserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use App\Models\OrderDetail;
use Illuminate\Support\Facades\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\User;

class OrderUserController extends Controller
{
    //
    public function order_user(Request $request){  // ngày tháng mua hàng
        $user = auth()->user();
        if(!Session::get('user_id')){
            $orders = Order::where('user_id', $user->id)
                    ->orderBy('id', 'desc')
                    ->paginate(4);

            if (!empty($request->date)){
            $orders = Order::where('created_at' , 'like' , '%' . $request->date . '%')
                        ->orderBy('created_at', 'desc')
                        ->paginate(4);
            }   
            return view('order_user.index')->with([
                'user'          =>  $user,
                'orders'        =>  $orders,
            ]);    
        }else{
            
        }
    }
    
    public function detailOrder($id){ // chi tiết đơn hàng vừa mua
        $data = [];
        $order = Order::whereId($id)
            ->with('order_detail')
            ->first();

        $total = $this->calculateTotalCart($order);

        $data['order'] = $order;
        $data['total'] = $total;

        return view('order_user.detail',$data);
    }

    public function calculateTotalCart($order)  // tổng tiền 
    {
        $total = 0;
        if (!is_null($order)) {
            foreach ($order->order_detail as $key => $order) {
                $total += $order['quantity'] * $order['price_id'];
            }
        }
        return $total;
    }


    public function profile(){ // thông tin khách hàng
        $data = [];
        $user = Auth::user();

        if(!session::get('id')){
            $users = User::where('id', $user->id)
                    ->orderBy('id', 'desc')
                    ->get();

            $data['users'] = $users;

            // dd($users);
        return view('profile.index',$data);
        }else{
            
            echo 'try again';
        }
        
    }
 
}

resources/views/order_user/_search.blade.php
<nav class="navbar navbar-light bg-light justify-content-between">
    {{-- <a class="navbar-brand">Navbar</a> --}}
    <form class="form-inline">
      {{-- <input class="form-control mr-sm-2" name ="name" type="search" placeholder="name" aria-label="Search"> --}}
      <br>
      <input type="date" class="form-control mr-sm-2" name="date" type="search" placeholder="date" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </nav>

resources/views/order_user/_table.blade.php
<table id="product-list" class="   table table-bordered table-hover table-striped">
    <thead class="table-primary">
        <tr>

            <th>STT</th>
            <th>Order day</th>
            <th>Status</th>
            <th>Detail</th>
            {{-- <th colspan="3">Action</th> --}}
        </tr>
    </thead>
    <tbody>
        @if(!empty($orders))
            @foreach ($orders as $key => $order)
                <tr>
                    {{-- <td>{{ $order->id }}</td> --}}
                    <td>{{ $key+1 }}</td>

                    <td>{{ $order->created_at }}</td>
                    <td>
                        @include('order_user.parts.alert_order_status')
                    </td>
                     <td>
                        <a href="{{ route('order_user.detail_order', ['id' => $order->id]) }}" class="btn btn-outline-primary" > Detail</a>                        
                    </td>
                  
                </tr>
            @endforeach
        @endif
    </tbody>

</table>
<br>
<a href="{{ route('index') }}" type="button" class="btn btn-info float-left" >Back</a>

<br>
<br>

<div style="margin-left:40%">{{ $orders->links() }}</div>

resources/views/order_user/detail.blade.php
@extends('layouts.master')

{{-- set page title --}}
@section('title', 'Detail Order')

{{-- set breadcrumbName --}}

@section('breadcrumbName', 'Order Detail')

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', 'Detail Order')

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/backend/css/orders/order-list.css">
@endpush

{{-- import file js (private) --}}
@push('js')
    <script src="/backend/js/orders/order-list.js"></script>
@endpush

@section('content')

    <hr><br> <br>
    <h4>Order details</h4>
    <br>
    {{-- show message --}}
    @include('errors.error')

    {{-- display form orderDetail --}}
    
    <table id="category-list" class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>STT</th>
                <th>product Name</th>
                <th>Image</th>
                <th>quantity</th>
                <th>price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($order->order_detail as $key => $order)
                <tr>
                    <td>{{$key+1}}</td>
                    <td><img src="/{{$order->product->image}}" width="150px" alt=""></td>
                    <td>{{$order->product->name}}</td>
                    <td>{{$order->quantity}}</td>
                    <td>{{$order->price_id}} VND</td>
                    <td>{{$order->total}} VND</td>
                </tr>
            @endforeach

        </tbody>
    </table>
    <h4 class="table-striped" style="float: right;"><b>TOTAL BILL:</b> {{ number_format($total) . ' VND' }}</h4>
    <hr>
    <br>

    <button class="btn btn-info"><a href="{{route('order_user.list_order')}}">BACK</a></button>
@endsection

resources/views/order_user/index.blade.php
@extends('layouts.master')

{{-- set page title --}}
@section('title', 'List Order')

{{-- set breadcrumbName --}}
@section('breadcrumbName', 'Order ')

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', 'List Order')

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/backend/css/orders/order-list.css">
@endpush

{{-- import file js (private) --}}
@push('js')
    <script src="/backend/js/orders/order-list.js"></script>
@endpush

@section('content')

    @include('errors.error')
    <hr>
    <br><br>
    <h4>My Order</h4>
    <br>
    @include('order_user._search')
    <br>
    @include('order_user._table')

    {{-- modal update order status  --}}

    {{-- @include('order_user.parts.modal_update_order_status') --}}

<hr>
@endsection