routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\PromotionController;
use App\Http\Controllers\Admin\MyController;
use App\Http\Controllers\Admin\UserExcelController;
use App\Http\Controllers\Admin\ConmmentController;

Route::group(['middleware' => ['check_login_admin'] , 'as' => 'admin.'], function () {

    Route::get('login', [AuthController::class, 'getLogin'])->name('login');
    Route::post('login', [AuthController::class, 'postLogin'])->name('login.handle');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');
	
	// Admin Dashboard
	Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/roleadmin', [DashboardController::class, 'role'])->name('roleadmin'); 

    // middleware check_role_sales: nếu role!= 1 && role != 2 thì không đc vào
    Route::middleware(['check_role_editer'])->group(function () { 
        Route::group(['prefix'=> 'category', 'as'=> 'category.'], function () {
            Route::get('/list', [CategoryController::class, 'index'])->name('index');
            Route::get('/create', [CategoryController::class, 'create'])->name('create');
            Route::post('/store', [CategoryController::class, 'store'])->name('store');
            Route::get('/show/{id}', [CategoryController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [CategoryController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [CategoryController::class, 'destroy'])->name('destroy');
        });

        Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
            Route::get('/list', [ProductController::class, 'index'])->name('index');
            Route::get('/create', [ProductController::class, 'create'])->name('create');
            Route::post('/store', [ProductController::class, 'store'])->name('store');
            Route::get('/show/{id}', [ProductController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [ProductController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix'=> 'message', 'as' => 'message.'], function () {
            route::get('/message',[MessageController::class, 'message'])->name('message');
        });
        Route::group(['prefix'  =>  'promotion'    ,   'as'    =>  'promotion.']  ,function(){
            route::get('/',[PromotionController::class,'promotion'])->name('list_promotion');
            Route::get('/create', [PromotionController::class, 'create'])->name('create');
            Route::post('/store', [PromotionController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [PromotionController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [PromotionController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [PromotionController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix'  =>  'comment', 'as' => 'comment.'], function (){
            Route::get('/', [ConmmentController::class, 'index'])->name('comment');
            Route::delete('/delete/{id}', [ConmmentController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
            Route::delete('/delete/{id}', [OrderController::class, 'destroy'])->name('destroy');
        });
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('/list', [OrderController::class, 'index'])->name('index');
        Route::get('/show/{id}', [OrderController::class, 'show'])->name('show');
        Route::get('/edit/{id}', [OrderController::class, 'edit'])->name('edit');
        Route::put('/update/{id}', [OrderController::class, 'update'])->name('update');
        // Route::delete('/delete/{id}', [OrderController::class, 'destroy'])->name('destroy');
    });
    // middleware admin: nếu role khác 1 thì không đc vào
    Route::middleware(['check_role_admin'])->group(function () { 
        Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
            Route::get('/list', [CustomerController::class, 'index'])->name('index');

            // Route::get('/create', [CustomerController::class, 'create'])->name('create');
            // Route::post('/store', [CustomerController::class, 'store'])->name('store');
            // Route::get('/search', [CustomerController::class, 'search'])->name('search');

            // Route::get('/show/{id}', [CustomerController::class, 'show'])->name('show');
            // Route::get('/edit/{id}', [CustomerController::class, 'edit'])->name('edit');
            // Route::put('/update/{id}', [CustomerController::class, 'update'])->name('update');
            
            Route::delete('/delete/{id}', [CustomerController::class, 'destroy'])->name('destroy');
        });

        Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
            Route::get('/list', [UserController::class, 'index'])->name('index');
            Route::get('/create', [UserController::class, 'create'])->name('create');
            Route::post('/store', [UserController::class, 'store'])->name('store');
            Route::get('/show/{id}', [UserController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [UserController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [UserController::class, 'destroy'])->name('destroy');

        });
            // excel Admin
            Route::get('/importExportView', [MyController::class, 'importExportView'])->name('importExportView');
            Route::get('/export', [MyController::class, 'export'])->name('export');
            Route::post('/import', [MyController::class, 'import'])->name('import');

            //excel user
            Route::get('CustomerExcel', [UserExcelController::class, 'importExportView'])->name('customerExcel');
            Route::get('ExportCustomer', [UserExcelController::class, 'ExportCustomer'])->name('ExportCustomer');
            Route::post('ImportCustomer', [UserExcelController::class, 'ImportCustomer'])->name('ImportCustomer');    
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderUserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\MessageController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/', [HomeController::class, 'index'])->name('index');

Route::group(['prefix' => 'home', 'as' => 'home.'], function () {
    
    Route::get('shop/{id}', [HomeController::class, 'shop'])->name('shop');

    });

Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('/detail/{id}', [ProductController::class, 'detail'])->name('detail');
    Route::post('/review', [ProductController::class, 'review'])->name('review');
    Route::get('/delete-comment/{id}', [ProductController::class, 'deleteComment'])->name('delete-comment');
    Route::get('/search', [ProductController::class, 'searchProduct'])->name('search'); 
    Route::get('/category/{id}', [ProductController::class, 'getProductByCategory'])->name('category'); 
        
    });
// route goij ddeens show ddaau hungf h
Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', [CartController::class, 'CartInfo'])->name('cart-info'); 
    Route::post('cart/{id}', [CartController::class, 'addCart'])->name('add-cart');
    Route::get('checkout', [CartController::class, 'checkout'])->name('checkout')->middleware('check_order');
    Route::post('checkout-complete', [CartController::class, 'Complete'])->name('checkout-complete');
    Route::post('send-verify-code', [CartController::class, 'sendVerifyCode'])->middleware(['auth'])->name('send-verify-code');
    Route::post('confirm-verify-code', [CartController::class, 'confirmVerifyCode'])->middleware(['auth'])->name('confirm-verify-code');
    Route::post('/delete', [CartController::class, 'destroy'])->name('destroy');
    
    });

Route::group(['prefix'  =>  'order_user', 'middleware' => 'auth',  'as'    =>  'order_user.']  ,function(){
    route::get('/',[OrderUserController::class,'order_user'])->name('list_order');
    route::get('/detail/{id}',[OrderUserController::class,'detailOrder'])->name('detail_order');
    Route::get('/profile',[OrderUserController::class,'profile'])->name('profile');
    Route::get('/edit', [OrderUserController::class, 'edit'])->name('edit');
    });

Route::group(['prefix'=>'contact', 'as'=> 'contact.'],function () {

        Route::get('/',[ContactController::class, 'contact'])->name('address');
        Route::post('/postmessage',[ContactController::class, 'postmessage'])->name('postmessage');
    });

Route::group(['prefix' =>'password','as'=>'password.'],function () {

    Route::get('/',[PasswordController::class, 'change'])->name('password');
    route::get('/detail/{id}',[PasswordController::class,'detailpassword'])->name('detailchange');
    Route::put('/update/{id}', [PasswordController::class, 'update'])->name('store');
});





app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Product extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'products';
    
    protected $fillable = [
        'name',
        'description',
        'image', // dat la so it ay : image hoac thumbnail ---> sua lai file migrate, reset lai DB
        'price',
        'status',
        'quantity',
        'hot',
        'category_id',
    ];
    

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    
    public function product_images(){
        return $this->hasMany(ProductImage::class);
    }
    /**
     * Get the post_detail for the post.
     */
    public function product_detail()
    {
        return $this->hasOne(ProductDetail::class);
    }
    public function price()
    {
        return $this->hasOne(Price::class);
    }
    
    public function order_detail()
    {
        return $this->hasMany(OrderDetail::class);
    }

    public function productPromotion()
    {
        return $this->belongsTo(ProductPromotion::class);
    }

    public function  promotions()
    {
        return $this->belongsToMany(Promotion::class);
    }

    public function  comments()
    {
        return $this->hasMany(Comment::class);
    }
  
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Product;
use Illuminate\Support\Facades\Session;
use App\Models\ProductDetail;
use App\Models\ProductImage;
use App\Models\Comment;
use Carbon\Carbon;

use App\Models\Price;

class ProductController extends Controller
{
    
    //
    public function detail($id, Request $request){
        $data = [];

        $categories = Category::all();
       
        $product = Product::where('products.id', $id)
                        ->with('product_images')
                        ->with('product_detail')
                        ->first();
        $related = Product::all();
        // dd($product);
        $now = Carbon::now(); // hiển thị thời gian comment trong  deltail sản phẩn
        $comment = Comment::where('product_id', $product->id)->with('user')->orderBy('id', 'desc' )->get(); //show thông tin user commnet
        $countcomment = new Comment();
        $data['countcomment'] = $countcomment;
        $data['now']        = $now; // giá goj
        $data['related']    = $related;
        $data['comment']    = $comment;
        $data['product']    = $product;
        $data['categories']  = $categories;

        return view('products.detail', $data);
    }

   
    public function searchProduct(Request $request)
    {
        $key = $request->key;

        $categories = Category::all();
        $productLimit   = Product::orderBy('created_at', 'desc')->limit(9)
        ->get();
        $products = Product::where('name', 'like', '%'. $key . '%')
                    ->orWhere('price', 'like', '%' .$key. '%')
                    ->paginate(10);
        $lasterProduct  = $this->formatDataProduct($productLimit);

        return view('home.listproductsearch', with([
            'products'=>$products,
            'categories' => $categories,
            'lasterProduct' => $lasterProduct,

        ]));
    }
  
    /**
     * formatDataProduct
     *
     *  @param Product $products
     *
     * @return mixed
     */
    public function formatDataProduct($products)
    {
        $productFormat = [];
        for ($i=1; $i <= 3; $i++) { 
            foreach ($products as $key => $value) {
                if ($key+1 <= $i*3 && $key >= ($i-1)*3) {
                    $productFormat[$i][$key] = $value;
                }
            }
        }
        return $productFormat;
    }


    public function getProductByCategory($id)
    {     
        $products   = Product::where('category_id', $id)
                            ->limit(8)
                            ->get();

        $view = view("home._ajax_product", compact('products'))->render();//gán lại $product với category_id đã chọn
        return response()->json(['status' => 'success','html' => $view]);
    }

    public function review(Request $request)
    {
        try {
            if (!auth()->user()) { 
                // nếu thằng user này  đã dăng nhâp thì  nó sẽ dc comment ngược lại chưa đăng nhập nó sẽ trả về  thông báo hoặc fomr login
                // return redirect()->back()->with(['message' => 'Chưa dăng nhập']);
                return redirect()->route('login')->with('message',' vui lòng đăng nhập để được đánh giá sản phẩm');

            }
            $user = auth()->user();
            $data = [
                'product_id'  => $request->product_id,
                'user_id'  => $user->id,
                'description'  => $request->description,
                'rate'  => $request->rate
            ];
            $review = Comment::create($data);
            if ($review) {
                return redirect()->back()->with(['message' => 'success']);
            }
            return redirect()->back()->with(['message' => 'Errors']);
        } catch (\Throwable $th) {
             info($th);
            return redirect()->back()->with(['message' => 'Errors']);
        }
    }

    public function delelteComment($id)
    {
        try {
            $comment = Comment::find($id);
            $comment->delete();
            return redirect()->back();
        } catch (\Exception $e) {
            info($e);
            return redirect()->back();
        }
    }

    
}

resources/views/products/detail.blade.php
@extends('layouts.master')
{{-- set page title --}}
@section('title', $product->name)

@section('content')
    <hr>
    <section class="product-detail">
        <div class="row">

            <div class="col-lg-6 col-md-6">
                <div class="product__details__pic__item">
                    <img class="product__details__pic__item--large" src="{{ asset($product->image) }}" width=" 350px" height="400px"
                        alt="{{ $product->image }}">
                </div>
                <hr>
                <div class="product__details__pic__slider owl-carousel">

                    @foreach ($product->product_images as $url)

                        <img data-imgbigurl="{{ asset($url->url) }}" src="{{ asset($url->url) }}" alt="" width="250px"
                            height="120px">

                    @endforeach
                </div>
                <hr>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="product__details__text">
                    <form action="{{ route('cart.add-cart', $product->id) }}" method="POST">
                        @csrf
                        <h3><strong>{{ $product->name }}</strong></h3>
                        <div class="product__details__rating">
                            @for ($i = 0; $i < 5; $i++)
                                <i class="{{ ($countcomment->startReview($product->id) > $i) ? 'fa fa-star' : 'fa fa-star-half-o' }}"></i> 
                                {{-- $countcomment -> startReview  chỉ đến id sản phẩm   nếu lớn  hơn $id nó sẽ show ra ngược lại ẩn --}}
                                {{-- startReview     là ham khai báo biến từ App/Models/Comment   hàm for    đếm giá tri--}}
                            @endfor
                            <span>({{ count($comment) }} reviews)</span>
                        </div>
                        <hr>
                        <p class="product-comment">
                            <span>{{ $product->description }}</span>
                        </p>
                        <p class="product-comment">
                            <span>Quantity Remaining: </span>
                            @if ($product->quantity <= 0)
                                <span class="text-danger">Out of stock</span>
                            @else
                                <span>{{ $product->quantity }}</span>
                            @endif
                        </p>
                        <hr>
                        @if (!empty($product->discount))
                            <p class="product-price text-muted"><del>{{ number_format($product->price) . '   VND' }}</del></p>
                            <p class="product-price">{{ number_format($product->discount) . 'VND' }}</p>
                        @else
                            <p class="product-price">{{ number_format($product->price) . '   VND' }}</p>
                        @endif
                        <hr>
                        <p>
                        <div class="product__details__quantity">
                            <div class="quantity">
                                <div class="pro-qty">
                                    <input type="number" name="quantity" required value="1"
                                        max="{{ $product->quantity }}">
                                </div>
                            </div>
                        </div>
                        <button class="btn btn-outline-success" type="submit">Add Cart</button>
                        </p>
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="product__details__tab">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab"
                                aria-selected="true">Information</a>
                        </li>
                        {{-- <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab"
                                aria-selected="false">Information</a>
                        </li> --}}
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab" aria-selected="false">Reviews
                                <span>(1)</span></a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tabs-1" role="tabpanel">
                            <div class="product__details__tab__desc">
                                <h6>Products Infomation</h6>
                                <p>{{ $product->product_detail->content }}</p>
                            </div>
                        </div>
                        {{-- <div class="tab-pane" id="tabs-2" role="tabpanel">
                            <div class="product__details__tab__desc">
                                <h6>Products Infomation</h6>
                                <p>{{ $product->product_detail->content }}</p>

                            </div>
                        </div> --}}
                        <div class="tab-pane" id="tabs-3" role="tabpanel">
                            <div class="product__details__tab__desc">
                                <h6>Products Infomation</h6>
                                <form action="{{ route('product.review') }}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    <input type="hidden" name="product_id" value="{{ $product->id }}">
                                 
                                    <div class="rate">
                                        <span>Evaluate : </span>
                                        <br>
                                        <input type="radio" id="star5" name="rate" value="5" />
                                        <label for="star5" title="text">5 stars</label>
                                        <input type="radio" id="star4" name="rate" value="4" />
                                        <label for="star4" title="text">4 stars</label>
                                        <input type="radio" id="star3" name="rate" value="3" />
                                        <label for="star3" title="text">3 stars</label>
                                        <input type="radio" id="star2" name="rate" value="2" />
                                        <label for="star2" title="text">2 stars</label>
                                        <input type="radio" id="star1" name="rate" value="1" />
                                        <label for="star1" title="text">1 star</label><br>
                                    </div><br><br><br>
                                    <label for="comment">Comment:</label>
                                    <textarea class="form-control" rows="5" id="comment" name="description"></textarea>
                                    <br>
                                    {{-- <label for="comment">đính kèm ảnh:</label>
                                    <input id="my-input" class="form-control" type="file" name="image"> --}}
                                        <button type="submit" class="btn btn-primary">Create</button>
                                </form>
                                <br>
                                <h4>Assessment form</h4>
                                <table class="table table-bordered table-hover table-striped">
                                    {{-- <thead>
                                        <th></th>
                                    </thead> --}}
                                    <tbody>
                                        @foreach ($comment as $item)

                                            <tr>
                                                <td>{{ $item->user->name }}</td>
                                                <td>{{ $item->description }}</td>
                                                <td>
                                                    <div class="product__details__text">
                                                        <div class="product__details__rating">
                                                            @for ($i = 0; $i < 5; $i++)
                                                                <i
                                                                    class="{{ $item->rate > $i ? 'fa fa-star' : 'fa fa-star-half-o' }}"></i> 
                                                                    {{-- $countcomment -> startReview  chỉ đến id sản phẩm   nếu lớn  hơn $id nó sẽ show ra ngược lại ẩn --}}
                                                            @endfor
                                                        </div>
                                                    </div>
                                                </td>
                                                <td>{{ $item->created_at->diffForHumans($now) }}</td>
                                                <td>
                                                    <a href="{{ route('product.delete-comment', $item->id) }}">Delete</a> 
                                                    {{--  viêt  function bên productcontroller  --}}
                                                </td>
                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <br><br><br> <br><br>

    <section class="categories">

        <div class="container">
            <div class="col-lg-12">
                <div class="section-title related__product__title">
                    <h2>Related Product</h2>
                </div>
            </div>
            <div class="row">

                <div class="categories__slider owl-carousel">
                    @if (!empty($related))

                        @foreach ($related as $item)

                            <div class="col-lg-3">
                                <div class="categories__item set-bg" data-setbg="{{ asset($item->image) }}">

                                    <h5><a href="{{ route('product.detail', $item->id) }}">{{ $item->category->name }}</a>
                                    </h5>

                                </div>
                            </div>

                        @endforeach

                    @endif
                </div>
            </div>
        </div>
    </section>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .rate {
            float: left;
            height: 46px;
            padding: 0 10px;
        }

        .rate:not(:checked)>input {
            position: absolute;
            top: -9999px;
        }

        .rate:not(:checked)>label {
            float: right;
            width: 1em;
            overflow: hidden;
            white-space: nowrap;
            cursor: pointer;
            font-size: 30px;
            color: #ccc;
        }

        .rate:not(:checked)>label:before {
            content: '★ ';
        }

        .rate>input:checked~label {
            color: #ffc700;
        }

        .rate:not(:checked)>label:hover,
        .rate:not(:checked)>label:hover~label {
            color: #deb217;
        }

        .rate>input:checked+label:hover,
        .rate>input:checked+label:hover~label,
        .rate>input:checked~label:hover,
        .rate>input:checked~label:hover~label,
        .rate>label:hover~input:checked~label {
            color: #c59b08;
        }

        /* Modified from: https://github.com/mukulkant/Star-rating-using-pure-css */

    </style>
@endsection

@push('css')
    <link rel="stylesheet" href="{{ '/shop/css/rating.css' }}">
@endpush

@push('js')

@endpush