routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\PromotionController;
use App\Http\Controllers\Admin\MyController;
use App\Http\Controllers\Admin\UserExcelController;
use App\Http\Controllers\Admin\ConmmentController;

Route::group(['middleware' => ['check_login_admin'] , 'as' => 'admin.'], function () {

    Route::get('login', [AuthController::class, 'getLogin'])->name('login');
    Route::post('login', [AuthController::class, 'postLogin'])->name('login.handle');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');
	
	// Admin Dashboard
	Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/roleadmin', [DashboardController::class, 'role'])->name('roleadmin'); 

    // middleware check_role_sales: nếu role!= 1 && role != 2 thì không đc vào
    Route::middleware(['check_role_editer'])->group(function () { 
        Route::group(['prefix'=> 'category', 'as'=> 'category.'], function () {
            Route::get('/list', [CategoryController::class, 'index'])->name('index');
            Route::get('/create', [CategoryController::class, 'create'])->name('create');
            Route::post('/store', [CategoryController::class, 'store'])->name('store');
            Route::get('/show/{id}', [CategoryController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [CategoryController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [CategoryController::class, 'destroy'])->name('destroy');
        });

        Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
            Route::get('/list', [ProductController::class, 'index'])->name('index');
            Route::get('/create', [ProductController::class, 'create'])->name('create');
            Route::post('/store', [ProductController::class, 'store'])->name('store');
            Route::get('/show/{id}', [ProductController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [ProductController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix'=> 'message', 'as' => 'message.'], function () {
            route::get('/message',[MessageController::class, 'message'])->name('message');
        });
        Route::group(['prefix'  =>  'promotion'    ,   'as'    =>  'promotion.']  ,function(){
            route::get('/',[PromotionController::class,'promotion'])->name('list_promotion');
            Route::get('/create', [PromotionController::class, 'create'])->name('create');
            Route::post('/store', [PromotionController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [PromotionController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [PromotionController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [PromotionController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix'  =>  'comment', 'as' => 'comment.'], function (){
            Route::get('/', [ConmmentController::class, 'index'])->name('comment');
            Route::delete('/delete/{id}', [ConmmentController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
            Route::delete('/delete/{id}', [OrderController::class, 'destroy'])->name('destroy');
        });
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('/list', [OrderController::class, 'index'])->name('index');
        Route::get('/show/{id}', [OrderController::class, 'show'])->name('show');
        Route::get('/edit/{id}', [OrderController::class, 'edit'])->name('edit');
        Route::put('/update/{id}', [OrderController::class, 'update'])->name('update');
        // Route::delete('/delete/{id}', [OrderController::class, 'destroy'])->name('destroy');
    });
    // middleware admin: nếu role khác 1 thì không đc vào
    Route::middleware(['check_role_admin'])->group(function () { 
        Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
            Route::get('/list', [CustomerController::class, 'index'])->name('index');

            // Route::get('/create', [CustomerController::class, 'create'])->name('create');
            // Route::post('/store', [CustomerController::class, 'store'])->name('store');
            // Route::get('/search', [CustomerController::class, 'search'])->name('search');

            // Route::get('/show/{id}', [CustomerController::class, 'show'])->name('show');
            // Route::get('/edit/{id}', [CustomerController::class, 'edit'])->name('edit');
            // Route::put('/update/{id}', [CustomerController::class, 'update'])->name('update');
            
            Route::delete('/delete/{id}', [CustomerController::class, 'destroy'])->name('destroy');
        });

        Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
            Route::get('/list', [UserController::class, 'index'])->name('index');
            Route::get('/create', [UserController::class, 'create'])->name('create');
            Route::post('/store', [UserController::class, 'store'])->name('store');
            Route::get('/show/{id}', [UserController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [UserController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [UserController::class, 'destroy'])->name('destroy');

        });
            // excel Admin
            Route::get('/importExportView', [MyController::class, 'importExportView'])->name('importExportView');
            Route::get('/export', [MyController::class, 'export'])->name('export');
            Route::post('/import', [MyController::class, 'import'])->name('import');

            //excel user
            Route::get('CustomerExcel', [UserExcelController::class, 'importExportView'])->name('customerExcel');
            Route::get('ExportCustomer', [UserExcelController::class, 'ExportCustomer'])->name('ExportCustomer');
            Route::post('ImportCustomer', [UserExcelController::class, 'ImportCustomer'])->name('ImportCustomer');    
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderUserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\MessageController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/', [HomeController::class, 'index'])->name('index');

Route::group(['prefix' => 'home', 'as' => 'home.'], function () {
    
    Route::get('shop/{id}', [HomeController::class, 'shop'])->name('shop');

    });

Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('/detail/{id}', [ProductController::class, 'detail'])->name('detail');
    Route::post('/review', [ProductController::class, 'review'])->name('review');
    Route::get('/delete-comment/{id}', [ProductController::class, 'deleteComment'])->name('delete-comment');
    Route::get('/search', [ProductController::class, 'searchProduct'])->name('search'); 
    Route::get('/category/{id}', [ProductController::class, 'getProductByCategory'])->name('category'); 
        
    });
// route goij ddeens show ddaau hungf h
Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', [CartController::class, 'CartInfo'])->name('cart-info'); 
    Route::post('cart/{id}', [CartController::class, 'addCart'])->name('add-cart');
    Route::get('checkout', [CartController::class, 'checkout'])->name('checkout')->middleware('check_order');
    Route::post('checkout-complete', [CartController::class, 'Complete'])->name('checkout-complete');
    Route::post('send-verify-code', [CartController::class, 'sendVerifyCode'])->middleware(['auth'])->name('send-verify-code');
    Route::post('confirm-verify-code', [CartController::class, 'confirmVerifyCode'])->middleware(['auth'])->name('confirm-verify-code');
    Route::post('/delete', [CartController::class, 'destroy'])->name('destroy');
    
    });

Route::group(['prefix'  =>  'order_user', 'middleware' => 'auth',  'as'    =>  'order_user.']  ,function(){
    route::get('/',[OrderUserController::class,'order_user'])->name('list_order');
    route::get('/detail/{id}',[OrderUserController::class,'detailOrder'])->name('detail_order');
    Route::get('/profile',[OrderUserController::class,'profile'])->name('profile');
    Route::get('/edit', [OrderUserController::class, 'edit'])->name('edit');
    });

Route::group(['prefix'=>'contact', 'as'=> 'contact.'],function () {

        Route::get('/',[ContactController::class, 'contact'])->name('address');
        Route::post('/postmessage',[ContactController::class, 'postmessage'])->name('postmessage');
    });

Route::group(['prefix' =>'password','as'=>'password.'],function () {

    Route::get('/',[PasswordController::class, 'change'])->name('password');
    route::get('/detail/{id}',[PasswordController::class,'detailpassword'])->name('detailchange');
    Route::put('/update/{id}', [PasswordController::class, 'update'])->name('store');
});





app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'categories';

    protected $fillable = [
        'name',
    ];

    /**
     * Get the posts for the category.
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }

    /**
     * Get the posts for the category.
     */
    public function limitProducts()
    {
        return $this->hasMany(Product::class)
            ->take(8);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCategoryRequest;
use App\Http\Requests\Admin\UpdateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Method: GET
        $data = [];

        $categories = Category::get();

        $data['categories'] = $categories;

        return view('admin.categories.index', $data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Method: GET
        $data = [];

        return view('admin.categories.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategoryRequest $request)
    {
        // Method: POST
        // insert to DB
        $categoryInsert = [
            
            'name' => $request->category_name,
            'parent_id' => $request->parent_id,

        ];

        DB::beginTransaction();

        try {
            Category::create($categoryInsert);

            // insert into data to table category (successful)
            DB::commit();

            return redirect()->route('admin.category.index')->with('sucess', 'Insert into data to Category Sucessful.');
        } catch (\Exception $ex) {
            // insert into data to table category (fail)
            DB::rollBack();
            Log::error($ex->getMessage());
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
  
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Method: GET

        $data = [];
        
        $category = Category::findOrFail($id);

        $data['category'] = $category;

        return view('admin.categories.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        // Method: PUT

        DB::beginTransaction();

        try {
            // create $category
            $category = Category::find($id);
            // set value for field name
            $category->name = $request->category_name;
            $category->parent_id = $request->parent_id;

            $category->save();
            
            DB::commit();

            return redirect()->route('admin.category.index')
                ->with('success', 'Update Category successful!');
        } catch (\Exception $ex) {
            DB::rollBack();
            // have error so will show error message
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Method: DELETE
        DB::beginTransaction();

        try {
            
            $category = Category::find($id);

            if(!empty($category->products) >= 1){
                foreach($category->products as $value){
                    DB::rollBack();
                    return redirect()->route('admin.category.index')
                ->with('error', 'Delete Category error!');
                }
            }
                $category->delete();
                DB::commit();
                return redirect()->route('admin.category.index')
                ->with('success', 'Delete Category successful!');
            
               
        }catch (\Exception $ex) {
            DB::rollBack();
            // have error so will show error message
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }
    // public function destroy($id){
    //     $category = Category::find($id);
    //     // dd($category);
    //     if(isset($category->products)){
    //         dd($category->products);

    //         return redirect()->route('admin.category.index')
    //           ->with('error', 'Delete Category error!');
    //     }else{
    //         $category->delete();
    //         return redirect()->route('admin.category.index')
    //           ->with('success', 'Delete Category successful!');
    //     }
    // }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')

{{-- set page title --}}
@section('title', 'Create Category')

{{-- set breadcrumbName --}}
@section('breadcrumbName', 'Category Management')

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', 'Create Category')

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/css/categories/category-create.css">
@endpush

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">List Category</a></li>
        <li class="breadcrumb-item active" aria-current="page">Create</li>
        </ol>
  </nav>
    <h4>Create Category</h4>

    @include('errors.error')
    
    <form action="{{ route('admin.category.store') }}" method="post">
        @csrf
        <div class="form-group">
            <label for="">Category Name:</label>
            <input class="form-control" type="text" name="category_name" placeholder="category name">
        </div>

        <div class="form-group">
            <label for="">Parent_id:</label>
            <input class="form-control" type="text" name="parent_id" placeholder="parent_id">
        </div>

        <div class="form-group">
            <a href="{{ route('admin.category.index') }}" class="btn btn-secondary">List Category</a>
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </form>
@endsection

resources/views/admin/categories/detail.blade.php
@extends('admin.layouts.master')

{{-- set page title --}}
@section('title', 'Detail Category')

{{-- set breadcrumbName --}}
@section('breadcrumbName', 'Category Management')

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', 'Detail Category')

{{-- import file css (private) --}}
@push('css')

@endpush

@section('content')
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">List Category</a></li>
    <li class="breadcrumb-item active" aria-current="page">detail</li>
    </ol>
</nav>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')



{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/css/categories/category-edit.css">
@endpush

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">List Category</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit</li>
        </ol>
    </nav>
    <h4>Edit Category</h4>
    <form action="{{ route('admin.category.update', $category->id) }}" method="post">
        @csrf
        @method('PUT')
        <div class="form-group mb-3">
            <label for="">Category Name</label>
            <input type="text" name="category_name" value="{{ $category->name }}">
            @error('category_name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="form-group mb-3">
            <label for="">Parent_id</label>
            <input type="text" name="parent_id" value="{{ $category->parent_id }}">
            @error('parent_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>


        <div class="form-group">
            <a href="{{ route('admin.category.index') }}" class="btn btn-secondary">List Category</a>
            <input type="submit" name="submit" value="Update" class="btn btn-primary">
        </div>
    </form>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')

{{-- set page title --}}
@section('title', 'List Category')

{{-- set breadcrumbName --}}
@section('breadcrumbName', 'Category Management')

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', 'List Category')

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/css/categories/category-list.css">
@endpush

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">List Category</li>
        </ol>
   </nav>
    {{-- form search --}}

    {{-- create category link --}}
    {{-- case 1 --}}
    <p><a class="btn btn-outline-info" href="{{ route('admin.category.create') }}">Create</a></p>
    
    {{-- case 2 --}}
    {{-- <p><a href="/category/create">Create</a></p> --}}

    {{-- show message --}}
    @if(Session::has('success'))
        <p class="text-success">{{ Session::get('success') }}</p>
    @endif

    {{-- show error message --}}
    @if(Session::has('error'))
        <p class="text-danger">{{ Session::get('error') }}</p>
    @endif

    {{-- display list category table --}}
    <table id="category-list" class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Stt</th>
                <th>Category Name</th>
                {{-- <th>Parent_id</th> --}}
                <th>List Product</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
            @if(!empty($categories))
                @foreach ($categories as $key => $category)
                    <tr>
                        <td>{{ $key+1 }}</td>
                        <td>{{ $category->name }}</td>
                        {{-- <td>{{ $category->parent_id }}</td> --}}
                        <td><a class="btn btn-outline-info" href="{{ route('admin.product.index', ['category_id' => $category->id]) }}">View List Category</a></td>
                        {{-- <td><a class="btn btn-outline-info" href="{{ route('admin.category.show', $category->id) }}">Detail</a></td> --}}
                        <td><a class="btn btn-outline-info" href="{{ route('admin.category.edit', $category->id) }}">Edit</a></td>
                        <td>
                            <form action="{{ route('admin.category.destroy', $category->id) }}" method="post" >
                                @csrf
                                @method('DELETE')
                                <input type="submit" name="submit" value="Delete"  class="btn btn-outline-danger">
                            </form>
                        </td>
                    </tr>
                @endforeach
            @endif
        </tbody>
    </table>
@endsection