routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\PromotionController;
use App\Http\Controllers\Admin\MyController;
use App\Http\Controllers\Admin\UserExcelController;
use App\Http\Controllers\Admin\ConmmentController;

Route::group(['middleware' => ['check_login_admin'] , 'as' => 'admin.'], function () {

    Route::get('login', [AuthController::class, 'getLogin'])->name('login');
    Route::post('login', [AuthController::class, 'postLogin'])->name('login.handle');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');
	
	// Admin Dashboard
	Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/roleadmin', [DashboardController::class, 'role'])->name('roleadmin'); 

    // middleware check_role_sales: nếu role!= 1 && role != 2 thì không đc vào
    Route::middleware(['check_role_editer'])->group(function () { 
        Route::group(['prefix'=> 'category', 'as'=> 'category.'], function () {
            Route::get('/list', [CategoryController::class, 'index'])->name('index');
            Route::get('/create', [CategoryController::class, 'create'])->name('create');
            Route::post('/store', [CategoryController::class, 'store'])->name('store');
            Route::get('/show/{id}', [CategoryController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [CategoryController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [CategoryController::class, 'destroy'])->name('destroy');
        });

        Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
            Route::get('/list', [ProductController::class, 'index'])->name('index');
            Route::get('/create', [ProductController::class, 'create'])->name('create');
            Route::post('/store', [ProductController::class, 'store'])->name('store');
            Route::get('/show/{id}', [ProductController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [ProductController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix'=> 'message', 'as' => 'message.'], function () {
            route::get('/message',[MessageController::class, 'message'])->name('message');
        });
        Route::group(['prefix'  =>  'promotion'    ,   'as'    =>  'promotion.']  ,function(){
            route::get('/',[PromotionController::class,'promotion'])->name('list_promotion');
            Route::get('/create', [PromotionController::class, 'create'])->name('create');
            Route::post('/store', [PromotionController::class, 'store'])->name('store');
            Route::get('/edit/{id}', [PromotionController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [PromotionController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [PromotionController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix'  =>  'comment', 'as' => 'comment.'], function (){
            Route::get('/', [ConmmentController::class, 'index'])->name('comment');
            Route::delete('/delete/{id}', [ConmmentController::class, 'destroy'])->name('destroy');
        });
        Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
            Route::delete('/delete/{id}', [OrderController::class, 'destroy'])->name('destroy');
        });
    });

    Route::group(['prefix' => 'order', 'as' => 'order.'], function () {
        Route::get('/list', [OrderController::class, 'index'])->name('index');
        Route::get('/show/{id}', [OrderController::class, 'show'])->name('show');
        Route::get('/edit/{id}', [OrderController::class, 'edit'])->name('edit');
        Route::put('/update/{id}', [OrderController::class, 'update'])->name('update');
        // Route::delete('/delete/{id}', [OrderController::class, 'destroy'])->name('destroy');
    });
    // middleware admin: nếu role khác 1 thì không đc vào
    Route::middleware(['check_role_admin'])->group(function () { 
        Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
            Route::get('/list', [CustomerController::class, 'index'])->name('index');

            // Route::get('/create', [CustomerController::class, 'create'])->name('create');
            // Route::post('/store', [CustomerController::class, 'store'])->name('store');
            // Route::get('/search', [CustomerController::class, 'search'])->name('search');

            // Route::get('/show/{id}', [CustomerController::class, 'show'])->name('show');
            // Route::get('/edit/{id}', [CustomerController::class, 'edit'])->name('edit');
            // Route::put('/update/{id}', [CustomerController::class, 'update'])->name('update');
            
            Route::delete('/delete/{id}', [CustomerController::class, 'destroy'])->name('destroy');
        });

        Route::group(['prefix' => 'user', 'as' => 'user.'], function () {
            Route::get('/list', [UserController::class, 'index'])->name('index');
            Route::get('/create', [UserController::class, 'create'])->name('create');
            Route::post('/store', [UserController::class, 'store'])->name('store');
            Route::get('/show/{id}', [UserController::class, 'show'])->name('show');
            Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
            Route::put('/update/{id}', [UserController::class, 'update'])->name('update');
            Route::delete('/delete/{id}', [UserController::class, 'destroy'])->name('destroy');

        });
            // excel Admin
            Route::get('/importExportView', [MyController::class, 'importExportView'])->name('importExportView');
            Route::get('/export', [MyController::class, 'export'])->name('export');
            Route::post('/import', [MyController::class, 'import'])->name('import');

            //excel user
            Route::get('CustomerExcel', [UserExcelController::class, 'importExportView'])->name('customerExcel');
            Route::get('ExportCustomer', [UserExcelController::class, 'ExportCustomer'])->name('ExportCustomer');
            Route::post('ImportCustomer', [UserExcelController::class, 'ImportCustomer'])->name('ImportCustomer');    
    });
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\OrderUserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\PromotionController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\MessageController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('/', [HomeController::class, 'index'])->name('index');

Route::group(['prefix' => 'home', 'as' => 'home.'], function () {
    
    Route::get('shop/{id}', [HomeController::class, 'shop'])->name('shop');

    });

Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('/detail/{id}', [ProductController::class, 'detail'])->name('detail');
    Route::post('/review', [ProductController::class, 'review'])->name('review');
    Route::get('/delete-comment/{id}', [ProductController::class, 'deleteComment'])->name('delete-comment');
    Route::get('/search', [ProductController::class, 'searchProduct'])->name('search'); 
    Route::get('/category/{id}', [ProductController::class, 'getProductByCategory'])->name('category'); 
        
    });
// route goij ddeens show ddaau hungf h
Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', [CartController::class, 'CartInfo'])->name('cart-info'); 
    Route::post('cart/{id}', [CartController::class, 'addCart'])->name('add-cart');
    Route::get('checkout', [CartController::class, 'checkout'])->name('checkout')->middleware('check_order');
    Route::post('checkout-complete', [CartController::class, 'Complete'])->name('checkout-complete');
    Route::post('send-verify-code', [CartController::class, 'sendVerifyCode'])->middleware(['auth'])->name('send-verify-code');
    Route::post('confirm-verify-code', [CartController::class, 'confirmVerifyCode'])->middleware(['auth'])->name('confirm-verify-code');
    Route::post('/delete', [CartController::class, 'destroy'])->name('destroy');
    
    });

Route::group(['prefix'  =>  'order_user', 'middleware' => 'auth',  'as'    =>  'order_user.']  ,function(){
    route::get('/',[OrderUserController::class,'order_user'])->name('list_order');
    route::get('/detail/{id}',[OrderUserController::class,'detailOrder'])->name('detail_order');
    Route::get('/profile',[OrderUserController::class,'profile'])->name('profile');
    Route::get('/edit', [OrderUserController::class, 'edit'])->name('edit');
    });

Route::group(['prefix'=>'contact', 'as'=> 'contact.'],function () {

        Route::get('/',[ContactController::class, 'contact'])->name('address');
        Route::post('/postmessage',[ContactController::class, 'postmessage'])->name('postmessage');
    });

Route::group(['prefix' =>'password','as'=>'password.'],function () {

    Route::get('/',[PasswordController::class, 'change'])->name('password');
    route::get('/detail/{id}',[PasswordController::class,'detailpassword'])->name('detailchange');
    Route::put('/update/{id}', [PasswordController::class, 'update'])->name('store');
});





app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Tymon\JWTAuth\Contracts\JWTSubject;
use App\Models\Comment;

class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Notifiable;

    use SoftDeletes;

    

    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'name',
        'email',
        'email_verified_at',
        'phone_number',
        'password',
        'remember_token',
        'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    public const PAGE_LIMIT = 10;
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Admin;
use Exception;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\Admin\StoreUserRequest;
use App\Http\Requests\Admin\UpdateCategoryRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(request $request)
    {
        //
        $data = [];
        //echo "day la manager User (Crud)";

        // $admins = Admin::paginate(8);
        $admins = Admin::orderBy('id', 'desc')->paginate(4);

        if(!empty($request->name)){
            $admins = Admin::where('name' , 'like' , '%' . $request->name . '%')
            ->orderBy('id', 'desc')
            ->paginate(4);
        }
        if(!empty($request->role_id)){
            $admins = Admin::where('role_id' , 'like' , '%' . $request->role_id . '%')
            ->orderBy('id', 'desc')
            ->paginate(4);
        }


        $data['admins'] = $admins;
        return view('admin.user.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {   $request->password = bcrypt('password');
        //
        $userInsert = [
            'name' => $request->name,
            'email'=> $request->email,
            'email_verified_at' => now(),
            'password' => $request->password,
            'role_id' => $request->role_id,
            'remember_token' => Str::random(10),
        ];
        DB::beginTransaction();
        //dd($userInsert);
        try{
            Admin::create($userInsert);
            DB::commit();
            return redirect()->route('admin.user.index')->with('sucess', 'Insert into data to Category Sucessful.');

        }catch(Exception $ex){
            echo $ex->getMessage();
        }
    }

    
    public function edit($id)
    {
        //
        $data = [];
        $users = Admin::find($id);
        
        $data['users'] = $users;
        return view('admin.user.edit',$data);
       
    }

    // /**
    //  * Update the specified resource in storage.
    //  *
    //  * @param  \Illuminate\Http\Request  $request
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function update(UpdateCategoryRequest $request, $id)
    {   $request->password = bcrypt('password');
        // dd($id);
        DB::beginTransaction();
        
        try{
            $users = Admin::findOrFail($id);
            // $users->name = $request->name;
            // $users->email = $request->email;
            $users->password = $request->password;
            $users->role_id = $request->role_id;


            $users->save();
            
            DB::commit();
            return redirect()->route('admin.user.index')->with('success', 'Update User successful!');
        }catch(Exception $ex){
            echo $ex->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        DB::beginTransaction();

        try {
            $admins = Admin::find($id);
            $admins->delete();
            DB::commit();

            return redirect()->route('admin.user.index')
                ->with('success', 'Delete User successful!');
        }  catch (\Exception $ex) {
            echo $ex->getMessage();
            DB::rollBack();
            // have error so will show error message
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }
}

resources/views/admin/user/_search.blade.php
<nav class="navbar navbar-light bg-light justify-content-between">
    {{-- <a class="navbar-brand">Sear</a> --}}
    <form class="form-inline" action="{{ route('admin.user.index') }}" method="GET">
      <input class="form-control mr-sm-2" name="name" type="search" placeholder="name" aria-label="Search">
      
      {{-- <input class="form-control mr-sm-2" name="role_id" type="search" placeholder="status" aria-label="Search"> --}}
      
      <div class="col-md-4">
        <select class="form-control" name="role_id">
            <option value="">Trạng thái</option>
            <option value="1" {{ !empty($role_id) && $role_id == 1}}>Admin</option>
            <option value="2" {{ !empty($role_id) && $role_id == 2}}>Editor</option>
            <option value="3" {{ !empty($role_id) && $role_id == 3}}>Shipper</option>
          </select>
      </div>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </nav>

resources/views/admin/user/alert_admin_status.blade.php

@if ($admin->role_id == \App\Models\Admin::STATUS[1])
    <div class="btn btn-success" role="alert">Admin</div>
@elseif ($admin->role_id == \App\Models\Admin::STATUS[2])
    <div class="btn btn-warning" role="alert">Editor</div>
@else
    <div class="btn btn-info" role="alert">shipper</div>
@endif

resources/views/admin/user/create.blade.php
@extends('admin.layouts.master')

{{-- set page title --}}
@section('title', 'Create User')

{{-- set breadcrumbName --}}
@section('breadcrumbName', 'create user')

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/admin/css/product/product-create.css">
@endpush
 
@section('content')
    <h4>Create User</h4>
    
    @include('errors.error')
    
    <form action="{{ route('admin.user.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group mb-5">
            <label for="">User Name</label>
            <input type="text" name="name" placeholder=" Enter Product name" value="{{ old('name') }}" class="form-control">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group mb-5">
            <label for="">Email</label>
            <input type="text" name="email" placeholder=" Enter Product email" value="{{ old('email') }}" class="form-control">
            @error('email')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group mb-5">
            <label for="">Password</label>
            <input type="password" name="password" placeholder=" Enter Product password" class="form-control">
            @error('password')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

           <div class="div">
            <input type="radio" id="vehicle1" name="role_id" value="0">
            <h3><label for="vehicle1">Admins</label></h3>
            <input type="radio" id="vehicle2" name="role_id" value="1">
            <h3><label for="vehicle2"> Editer</label></h3>
            <input type="radio" id="vehicle3" name="role_id" value="2">
            <h3><label for="vehicle3">Shipper</label></h3>
            </div> 
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.master')


{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/admin/css/product/product-create.css">
@endpush
 s
@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">List User</li>
            <li class="breadcrumb-item active" aria-current="page">Edit User</li>
        </ol>
    </nav>
    @include('errors.error')
    <form style="padding:100px" action="{{ route('admin.user.update', $users->id) }}" method="post">
        @csrf
        @method('PUT')
        {{-- <input name="_method" type="hidden" value="PUT"> --}}
     

        <div class="row">
            <div class="col-3">
                <label class="">User Name</label>
                <h5>{{$users->name}}</h5>
                
            </div>
            <div class="col-3">
                <label class=""> User Email</label>
                <h5>{{$users->email}}</h5>
                @error('email')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>    
        <div class="row">
            <div class="col-3">
                <label class="">Old Password</label>
                <input type="password" value="{{ old('password', $users->password) }}" placeholder=" Enter password" class="form-control">
            </div>
            <div class="col-3">
                <label class="">New Password</label>
                <input type="password" name="password" placeholder=" Enter new password" class="form-control">
                @error('password')
                    <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
        </div>

        <br>
        <div class="col-3">
            <label class="">Role_id</label>
            <input type="role_id" name="role_id" value="{{ old('password', $users->role_id) }}" placeholder=" Enter role_id" class="form-control">
           
            @error('role_id')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
    <hr>
    
@endsection

resources/views/admin/user/import.blade.php
@extends('admin.layouts.master')

@section('content')

   
<div class="container">
    <div class="card bg-light mt-3">
        <div class="card-header">
            Laravel 8 Import Export Excel to database Example - ItSolutionStuff.com
        </div>
        <div class="card-body">
            <form action="{{ route('admin.import') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <input type="file" name="file" class="form-control">
                <br>
                <button class="btn btn-success">Import Admins Data</button>
                <a class="btn btn-warning" href="{{ route('admin.export') }}">Export Admins Data</a>
            </form>
        </div>
    </div>
</div>
   
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.master')

    @section('content')
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">List User</li>
            </ol>
        </nav>
            {{-- show message --}}
            @if(Session::has('success'))
                <p class="text-success">{{ Session::get('success') }}</p>
            @endif

            {{-- show error message --}}
            @if(Session::has('error'))
                <p class="text-danger">{{ Session::get('error') }}</p>
            @endif
            {{-- search link --}}
            @include('admin.user._search')
            <p ><a  class="btn btn-outline-success" href="{{ route('admin.user.create') }}">Create</a></p>

            <button class="btn btn-warning" ><a href="{{route('admin.importExportView')}}">Export File Admin</a></button>
            <table id="user-list" class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>name</th>
                        <th>email</th>
                        <th>role_id</th>
                        <th>status</th>
                        <th>Create_date</th>
                        <th colspan="3">Action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach ($admins as $key=> $admin)
                        <tr>
                            <th>{{$key+1}}</th>
                            <th>{{$admin->name}}</th>
                            <th>{{$admin->email}}</th>
                            <th>{{$admin->role_id}}</th>
                            <th> @include('admin.user.alert_admin_status') </th>
                            <th>{{$admin->created_at}}</th>
                            
                            {{-- <td><a class="btn btn-outline-success" href="{{ route('admin.user.show', $admin->id) }}">Detail</a></td> --}}
                            <td><a class="btn btn-outline-secondary" href=" {{ route('admin.user.edit', $admin->id) }}">Change Password</a></td>
                            <td>
                                <form action="{{ route('admin.user.destroy', $admin->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <input type="submit" value="Delete" class="btn btn-outline-danger" onclick="return confirm('Are you sure DELETE User?')" class="btn btn-danger" />
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
        </table>
        {{$admins->links()}}
    @endsection    

resources/views/admin/user/show.blade.php
@extends('admin.layouts.master')

{{-- set page title --}}
@section('title', 'Show User')

{{-- set breadcrumbName --}}
@section('breadcrumbName', 'Show user')

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/admin/css/product/product-create.css">
@endpush

@section('content')
    <h4>Show detail User</h4>
    
    @include('errors.error')

   <h1> {{$users->name}}</h1>
   <h1>{{$users->email }}</h1>
    
@endsection